//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace project.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("project.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap _111025_phone_icon {
            get {
                object obj = ResourceManager.GetObject("111025_phone_icon", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap _2824438_academic_clip_exam_note_paper_icon {
            get {
                object obj = ResourceManager.GetObject("2824438_academic_clip_exam_note_paper_icon", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap _309041_users_group_people_icon {
            get {
                object obj = ResourceManager.GetObject("309041_users_group_people_icon", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap _352521_location_on_icon {
            get {
                object obj = ResourceManager.GetObject("352521_location_on_icon", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap _3915748_direction_globe_location_maps_navigation_icon {
            get {
                object obj = ResourceManager.GetObject("3915748_direction_globe_location_maps_navigation_icon", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap _6000107_coronavirus_home_jobs_teleworking_working_icon {
            get {
                object obj = ResourceManager.GetObject("6000107_coronavirus_home_jobs_teleworking_working_icon", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap _8541829_eye_vision_view_icon {
            get {
                object obj = ResourceManager.GetObject("8541829_eye_vision_view_icon", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap _8665352_eye_slash_icon {
            get {
                object obj = ResourceManager.GetObject("8665352_eye_slash_icon", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap _8673632_ic_fluent_person_filled_icon {
            get {
                object obj = ResourceManager.GetObject("8673632_ic_fluent_person_filled_icon", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap _897226_balance_spendings_budget_money_save_money_icon {
            get {
                object obj = ResourceManager.GetObject("897226_balance spendings_budget_money_save money_icon", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap _9004849_envelope_mail_message_email_icon {
            get {
                object obj = ResourceManager.GetObject("9004849_envelope_mail_message_email_icon", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TenCongViec,TenCongTy,DiaChi,MucLuong,MoTa,YeuCau,TenLienHe,SDT,Mail,DiaChiLienHe,Note,LinhVuc
        ///&quot;Software Engineer (Web, App) - Thủ Đức&quot;,CareerLink&apos;s Client,&quot;Thành Phố Thủ Đức,Hồ Chí Minh&quot;,&quot;15,000,000 VND - 18,000,000 VND&quot;,&quot;- Tham gia thiết kế và phát triển các dự án Web và Application của công ty.- Lập trình phát triển Web và ứng dụng bằng Winform hoặc WPF bằng công nghệ .NET/.NET Core/ASP.NET Core- Cập nhật, bảo trì và sửa lỗi các hệ thống hiện hành.- Nghiên cứu và ứng dụng công nghệ mới nhằm mục đích tối [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Congviec {
            get {
                return ResourceManager.GetString("Congviec", resourceCulture);
            }
        }
    }
}
